lane :runTests do
    gradle(task: "test")
end

lane :buildDebug do
    gradle(task: "clean assembleDebug")
end

lane :buildStaging do
    gradle(task: "clean assembleStaging")
end

lane :buildRelease do
    gradle(task: "clean assembleRelease")
end

lane :uploadToCrashlytics do
 crashlytics(
        apk_path: "app/build/outputs/apk/debug/app-debug.apk",
        groups: "fastlane-demo-testers",
        notifications: true
    )
end