lane :runTests do
    gradle(task: "test")
end

lane :buildDebug do
    gradle(task: "clean assembleDebug")
end

lane :buildStaging do
    gradle(task: "clean assembleStaging")
end

lane :buildRelease do
    gradle(task: "clean assembleRelease")
end

lane :uploadToCrashlytics do
 crashlytics(
        groups: "fastlane-demo-testers",
        notifications: true
    )
end